# Pact provider workflow - dynamically fetches pacts, based on consumer version selectors
# Test (verify pacts) -> Publish verification results -> Can-I-Deploy to Prod -> Record Deployment (master branch)

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      name: you54f/example-consumer-dotnet
      ref: refs/heads/templates

variables:
  - name: PACTICIPANT
    value: "pactflow-example-provider-dotnet"
  - name: PACT_BROKER_BASE_URL
    value: https://testdemo.pactflow.io
  - template: templates/azure_pact_variables.yml@templates

steps:
- script: printenv
- script: |
    dotnet restore src
    dotnet restore tests
  displayName: 📦  Restore
- script: |
    dotnet run --project src &
  displayName: 🏁  Start Provider
- script: |
    dotnet test tests
  displayName: ✅  Test
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)
    PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true

- template: templates/azure_pact_can_i_deploy_with_params.yml@templates
  parameters:
    to_environment: production
    application_name: $(PACTICIPANT)
    token: $(PACT_BROKER_TOKEN)
- template: templates/azure_pact_record_deployment_with_params.yml@templates
  parameters:
    environment: production
    application_name: $(PACTICIPANT)
    token: $(PACT_BROKER_TOKEN)